# Generated by Django 5.1.7 on 2025-03-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=320)),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateTimeField()),
            ],
        ),
    ]
