# Generated by Django 5.1.7 on 2025-04-08 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='person', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('google_id', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.URLField(blank=True, max_length=255, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
