services:
  db:
    image: postgres
    container_name: my-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-impexp:/home
    restart: on-failure:5
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  postgres-data:
    driver: "local"
    driver_opts:
      type: "none"
      device: "/home/user/data/pgsql/docker"
      o: "bind" 
  postgres-impexp:
    driver: "local"
    driver_opts:
      type: "none"
      device: "/home/user/data/pgsql/impexp"
      o: "bind" 
